etl/etl/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('etlapp/', include(('etlapp.urls', 'etlapp'), namespace='etlapp')),
    #path('templates/', include(('etlapp.urls', 'etlapp'), namespace='static_etlapp')),
    path('admin/', admin.site.urls),
]

etl/etlapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.save_file, name='save_file'),
    path('clear/', views.clear_database, name='clear_database'),
    path('refresh/', views.refresh_table, name='refresh_table'),
    path('dummy/', views.dummy, name='dummy'),
]

etl/etlapp/models.py
from django.db import models
from django.utils import datetime_safe

class Products(models.Model):
    ProductID = models.CharField(max_length=200, null=True, blank=True)
    Manufacturer = models.CharField(max_length=200, null=True, blank=True)
    Name = models.CharField(max_length=200, null=True, blank=True)
    Price = models.CharField(max_length=200, null=True, blank=True)
    Car_type = models.CharField(max_length=200, null=True, blank=True)
    season = models.CharField(max_length=200, null=True, blank=True)
    size = models.CharField(max_length=200, null=True, blank=True)
    approval = models.CharField(max_length=200, null=True, blank=True)
    speed_index = models.CharField(max_length=200, null=True, blank=True)
    weight_index = models.CharField(max_length=200, null=True, blank=True)
    sound_index = models.CharField(max_length=200, null=True, blank=True)
    production_year = models.CharField(max_length=200, null=True, blank=True)
    country_of_origin = models.CharField(max_length=200, null=True, blank=True)
    guaranty = models.CharField(max_length=200, null=True, blank=True)
    other_info = models.TextField(null=True, blank=True)
    pub_date = models.DateTimeField()
    def __str__(self):
        return (self.Manufacturer + " " + self.Name)

etl/etlapp/views.py
import datetime
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from openpyxl import Workbook
from .models import Products

from static.etlapp import ScrapperRedux1

def index(request):
    products_list = Products.objects.order_by('-pub_date')
    widths_list = ScrapperRedux1.get_tire_widths()
    # template = loader.get_template('etlapp/index.html')
    context = {
        'products_list': products_list,
        'widths_list': widths_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'etlapp/index.html', context)

def save_file(request):
    if request.method == "POST":
        data = {}        
        if request.POST['selected_product'] == ".TXT":
            product_id = Products.objects.get(id=request.POST['product_id'])
            txt_path = 'static/etlapp/files_from_database/dane.txt'
            generate_txt(product_id, txt_path)

            data = {
                "dfile": product_id.Name
            }
        else:
            generate_csv(Products.objects.all(), 'static/etlapp/files_from_database/oponeo.xls')
        return JsonResponse(data)

    return render(request, 'etlapp/index.html')

def generate_csv(Products, file_path):
    wb = Workbook()
    ws = wb.active
    row_count = 1

    ws['A' + str(row_count)] = "ID BD"
    ws['B' + str(row_count)] = "ID Oponeo"
    ws['C' + str(row_count)] = "Producent"
    ws['D' + str(row_count)] = "Nazwa"
    ws['E' + str(row_count)] = "Cena"
    ws['F' + str(row_count)] = "Typ pojazdu"
    ws['G' + str(row_count)] = "Sezon"
    ws['H' + str(row_count)] = "Rozmiar"
    ws['I' + str(row_count)] = "Homologacja"
    ws['J' + str(row_count)] = "Indeks prędkości"
    ws['K' + str(row_count)] = "Indeks nośności"
    ws['L' + str(row_count)] = "Etykieta UE"
    ws['M' + str(row_count)] = "Rok produkcji"
    ws['N' + str(row_count)] = "Kraj produkcji"
    ws['O' + str(row_count)] = "Gwarancja"
    ws['P' + str(row_count)] = "Inne"
    ws['Q' + str(row_count)] = "Data publikacji w bazie"
    row_count += 1

    for product in Products:
        ws['A' + str(row_count)] = product.id
        ws['B' + str(row_count)] = product.ProductID
        ws['C' + str(row_count)] = product.Manufacturer
        ws['D' + str(row_count)] = product.Name
        ws['E' + str(row_count)] = product.Price
        ws['F' + str(row_count)] = product.Car_type
        ws['G' + str(row_count)] = product.season
        ws['H' + str(row_count)] = product.size
        ws['I' + str(row_count)] = product.approval
        ws['J' + str(row_count)] = product.speed_index
        ws['K' + str(row_count)] = product.weight_index
        ws['L' + str(row_count)] = product.sound_index
        ws['M' + str(row_count)] = product.production_year
        ws['N' + str(row_count)] = product.country_of_origin
        ws['O' + str(row_count)] = product.guaranty
        ws['P' + str(row_count)] = product.other_info
        ws['Q' + str(row_count)] = product.pub_date
        row_count += 1

    wb.save(file_path)

def generate_txt(product, file_path):
    with open(file_path, 'w', encoding='utf-8') as file:
        file.write("Produkt: " + str(product.Name) + '\n\n')
        file.write("Id bazy danych: " + str(product.id) + "\n")
        file.write("Id OPONEO: " + str(product.ProductID) + "\n")
        file.write("Producent: " + str(product.Manufacturer) + "\n")
        file.write("Cena: " + str(product.Price) + "\n")
        file.write("Typ pojazdu: " + str(product.Car_type) + "\n")
        file.write("Sezon: " + str(product.season) + "\n")
        file.write("Rozmiar: " + str(product.size) + "\n")
        file.write("Homologacja: " + str(product.approval) + "\n")
        file.write("Indeks prędkości: " + str(product.speed_index) + "\n")
        file.write("Indeks nośności: " + str(product.weight_index) + "\n")
        file.write("Etykieta UE: " + str(product.sound_index) + "\n")
        file.write("Rok produkcji: " + str(product.production_year) + "\n")
        file.write("Kraj produkcji: " + str(product.country_of_origin) + "\n")
        file.write("Gwarancja: " + str(product.guaranty) + "\n")
        file.write("Inne: " + str(product.other_info) + "\n")
        file.write("Data publikacji w bazie: " + str(product.pub_date) + "\n")

def clear_database(request):
    if request.method == "POST":
        summary = str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + " Baza danych została wyczyszczona. Usunięto " + str(len(Products.objects.all())) + " rekordów.\n"
        Products.objects.all().delete()

        data = {
            summary:summary,
        }

        with open('static/etlapp/logs/db_session_logs.txt', 'r', encoding='utf-8') as session_logs:
            with open('static/etlapp/logs/logs.txt', 'a', encoding='utf-8') as logs:
                logs.write(session_logs.read())

        with open('static/etlapp/logs/db_session_logs.txt', 'w', encoding='utf-8') as file:
                file.write(summary)

        with open('static/etlapp/logs/db_session_logs.txt', 'r', encoding='utf-8') as file:
            content = [x.strip('\n') for x in file.readlines()]

        test = ""
        for x in content:
            test = test + x + "\n"

        data = {
            summary:test,
        }

        return JsonResponse(data)

    return render(request, 'etlapp/index.html')

def refresh_table(request):
    #increment = int(request.GET['append_increment'])
    #increment_to = increment + 10
    products_list = Products.objects.all().order_by('-pub_date')
    return render(request, 'etlapp/refresh_table.html', {'products_list': products_list})

tires = list()
data_list = list()
date = str(datetime.datetime.now())
def dummy(request):
    global data_list
    global tires
    if request.method == "POST":
        data = {}
        summary = ""

        if request.POST['button_text'] == "ETL":
            width = request.POST['dropdown_id']
            time = ScrapperRedux1.extract(tires, width)
            summary += str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + " Ekstrakcja zakończona. Sparsowano " + str(len(tires)) + " rekordów. Operacja zajęła " + str(int(time/60)) + " min " + str(int(time%60)) + " sekund.\n"
            data_list = ScrapperRedux1.transform(tires)
            summary += str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + " Transformacja zakończona. Przygotowano " + str(len(data_list[0])) + " obiektów. Operacja zajęła " + str(int(data_list[1]/60)) + " min " + str(int(data_list[1]%60)) + " sekund.\n"
            time = ScrapperRedux1.load(data_list[0], date)
            summary += str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + " Ładowanie zakończone. Operacja zajęła " + str(int(time/60)) + " min " + str(int(time%60)) + " sekund.\n"
            data_list = list()
            tires = list()

        elif request.POST['button_text'] == "EXTRACT":
            tire_widths = ScrapperRedux1.get_tire_widths()
            width = request.POST['dropdown_id']
            extract_time = ScrapperRedux1.extract(tires, width)
            summary += str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + " Ekstrakcja zakończona. Sparsowano " + str(len(tires)) + " rekordów. Operacja zajęła " + str(int(extract_time/60)) + " min " + str(int(extract_time%60)) + " sekund.\n"

        elif request.POST['button_text'] == "TRANSFORM":
            data_list = ScrapperRedux1.transform(tires)
            summary += str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + " Transformacja zakończona. Przygotowano " + str(len(data_list[0])) + " obiektów. Operacja zajęła " + str(int(data_list[1]/60)) + " min " + str(int(data_list[1]%60)) + " sekund.\n"

        else:
            time = ScrapperRedux1.load(data_list[0], date)
            summary += str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + " Ładowanie zakończone. Operacja zajęła " + str(int(time/60)) + " min " + str(int(time%60)) + " sekund.\n"
            data_list = list()
            tires = list()

        with open('static/etlapp/logs/db_session_logs.txt', 'a', encoding='utf-8') as file:
                file.write(summary)

        with open('static/etlapp/logs/db_session_logs.txt', 'r', encoding='utf-8') as file:
            content = [x.strip('\n') for x in file.readlines()]

        test = ""
        for x in content:
            test = test + x + "\n"

        data = {
            summary:test,
        }

        return JsonResponse(data)

    return render(request, 'etlapp/index.html')

etl/etlapp/templates/etlapp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'etlapp/custom.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  </head>

  <body>

  <br>

  <div class="mx-auto">
    <h1 class="text-center">PROCESY ETL</h1>
  </div>

  <br>

  <div class="mx-auto" style="width:350px">
    <select name="width" style="width:350px" id="dropdownWidth">
      {% for width in widths_list %}
        <option>{{ width }}</option>
      {% endfor %}
    </select>
  </div>

  <br>

  <div class="mx-auto" style="width:350px">
    <div class="btn-group">
      <button class="btn etlButton" id="extract">EXTRACT</button>
      <button class="btn etlButton" id="transform" disabled>TRANSFORM</button>
      <button class="btn etlButton" id="load" disabled>LOAD</button>
    </div>
  </div>

  <br>

  <div class="mx-auto" style="width:350px">
    <button class="btn btn-block etlButton" id="etl">ETL</button>
  </div>

  <br>

  <div class="mx-auto" style="width:750px">
    <textarea class="textBox" id="feedback" readonly></textarea>
  </div>

  <br>

  <div class="mx-auto" style="width:350px">
    <h3 class="text-center">RAPORT</h3>
  </div>

  <br>
  
    <div class="mx-auto" style="width:350px">
      <div>
        <button class="btn btn-rep btn-block" id="clicker" href="#">
          POBIERZ BAZĘ W FORMACIE XLS
        </button>
        <a href="#" id="rap1"></a>
      </div>
    </div>
  

  <br>

 
    <div class="mx-auto" style="width:350px">
      <button class="btn btn-danger btn-block" id="clearBase">CZYŚĆ BAZĘ</button>
    </div>


  <br>

  <div class="mx-auto" id="refreshTable">
      {% if products_list %}
          <table class="table table-hover table-sm" id="baseTable">
            <thead class="thead-dark">
              <tr>
                <th>ID BD</th>
                <th>Producent</th>
                <th>Nazwa</th>
                <th>Cena</th>
                <th>Sezon</th>
                <th>Rozmiar</th>
                <th>Indeks prędkości</th>
                <th>Indeks nośności</th>
                <th>Etykieta UE</th>
                <th>Data publikacji w bazie</th>
                <th>POBIERZ</th>
              </tr>
            </thead>
            <tbody>
              {% for product in products_list %}
              <tr>
                <th>{{ product.id }}</th>
                <th>{{ product.Manufacturer }}</th>
                <th>{{ product.Name }}</th>
                <th>{{ product.Price }}</th>
                <th>{{ product.season }}</th>
                <th>{{ product.size }}</th>
                <th>{{ product.speed_index }}</th>
                <th>{{ product.weight_index }}</th>
                <th>{{ product.sound_index }}</th>
                <th>{{ product.pub_date }}</th>
                <th>
                  <button class="btn downloadFile" id="clickTxt" name={{ product.id }}>.TXT</button>
                  <a href="#" class='save-txt'></a>
                </th>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
      <p>Brak danych do wyświetlenia.</p>
      {% endif %}
  </div>

  <script>
    $('#clicker').click(function(){
        var selected_product = $(this).text();
        $.ajax({
          type: "POST",
          url: "{% url 'etlapp:save_file' %}",
          data: {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            selected_product:selected_product,
          },
          success: function(data){
                $("#rap1").attr("href", "{% static 'etlapp/files_from_database/oponeo.xls' %}");
                $('#rap1').attr('download', "oponeo.xls");
                document.getElementById("rap1").click();
            }
          });
    });
  </script>

  <script>    
    $(".downloadFile").click(function(){
      var product_id = $(this.id);
      var selected_product = $(this).text();
      var selected_id = $(this).attr('name');
      var txt_path = "{% static 'etlapp/files_from_database/dane.txt' %}";
      var txt_name = String(selected_id) + ".txt";
        $.ajax({
          type: "POST",
          url: "{% url 'etlapp:save_file' %}",
          data: {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            selected_product:selected_product,
            product_id:selected_id,
          },
          success: function(data){
              $('.save-txt').attr("href", txt_path);
              $('.save-txt').attr('download', data['dfile'] + '.txt');
              document.getElementsByClassName('save-txt')[0].click();
            }
          });
    });
  </script>

  <script>
    $('#clearBase').click(function(){
        $.ajax({
          type: "POST",
          url: "{% url 'etlapp:clear_database' %}",
          data: {
            csrfmiddlewaretoken: '{{ csrf_token }}',
          },
          success: function(data){
            $.each(data, function( index, value ){
                $("#feedback").val($("#feedback").val()+value);
                var $textarea = $('#feedback');
                $textarea.scrollTop($textarea[0].scrollHeight);
            });
            location.reload();
            }
          });
    });
  </script>

  <script>
      $(document).ready(function() {
        $.ajax({
           url : "{% static 'etlapp/logs/db_session_logs.txt' %}",
           dataType: "text",
           success : function (data) {
               $("#feedback").text(data);
               var $textarea = $('#feedback');
               $textarea.scrollTop($textarea[0].scrollHeight);
           }
        });
      });
  </script>

 <script>
  $('.etlButton').click(function(){
    var button_text = $(this).text();
    var dropdown_id = $('#dropdownWidth').find(":selected").text()
    
    $(this).attr("disabled", true);
    $('#extract').attr("disabled", true);
    $('#etl').attr("disabled", true);
    
      $.ajax({
        type: "POST",
        url: "{% url 'etlapp:dummy' %}",
        data: {
          csrfmiddlewaretoken: '{{ csrf_token }}',
          button_text:button_text,
          dropdown_id:dropdown_id,
        },
        success: function(data){
            $.each(data, function( index, value ){
                $("#feedback").val(value);
                var $textarea = $('#feedback');
                $textarea.scrollTop($textarea[0].scrollHeight);
            });

            if (button_text === "EXTRACT") {
              $('#transform').attr("disabled", false); 
            } else if (button_text === "TRANSFORM") {
              $('#load').attr("disabled", false);
            } else if (button_text === "LOAD") {
              $('#load').attr("disabled", true);
              location.reload();
            } else {
              location.reload();
            }
          }
        });

    

  });
  </script> 

  </body>
</html>

etl/etlapp/templates/etlapp/refresh_table.html
{% load static %}
 
 <!--<div class="mx-auto" id="refreshTable">-->
    {% if products_list %}
        <table class="table table-hover table-sm" id="baseTable">
          <thead class="thead-dark">
            <tr>
              <th>ID BD</th>
              <th>Producent</th>
              <th>Nazwa</th>
              <th>Cena</th>
              <th>Sezon</th>
              <th>Rozmiar</th>
              <th>Indeks prędkości</th>
              <th>Indeks nośności</th>
              <th>Kraj produkcji</th>
              <th>Data publikacji w bazie</th>
              <th>POBIERZ</th>
            </tr>
          </thead>
          <tbody>
            {% for product in products_list %}
            <tr>
              <th>{{ product.id }}</th>
              <th>{{ product.Manufacturer }}</th>
              <th>{{ product.Name }}</th>
              <th>{{ product.Price }}</th>
              <th>{{ product.season }}</th>
              <th>{{ product.size }}</th>
              <th>{{ product.speed_index }}</th>
              <th>{{ product.weight_index }}</th>
              <th>{{ product.sound_index }}</th>
              <th>{{ product.pub_date }}</th>
              <th>
                <button class="btn downloadFile" id="clickTxt" name={{ product.id }}>.TXT</button>
                <a href="#" class='save-txt'></a>
              </th>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
     <p>Brak danych do wyświetlenia.</p>
    {% endif %}
<!--</div>-->